version: 2
jobs:
  test_with_node_10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm test
  test_with_node_12:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm test
  test_with_node_14:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm run test
  test_with_node_15:
    docker:
      - image: circleci/node:15
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm run test:coverage
      - run:
          name: Deploy coverage
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  test_all:
    jobs:
      - test_with_node_10
      - test_with_node_12
      - test_with_node_14
      - test_with_node_15
